name: Run Cadence tests
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Flow CLI
        run: |
          brew update
          brew install flow-cli
